### ISSUE TITLE
For total beginners

### ISSUE THREAD

**Issue by jubalh** [geajack/Wordology#6]
For total beginners who only know very little words it might be cool to have the 'lookup' feature available in a quicker way. Like hovering over it and already getting it translated?

**Comment by jack-jjm** [comment]
Haha. Sure, and then maybe a textbox where you can type stuff and it'll translate it into any language, and a tab you can go into with flashcards and integrated spaced repetition algorithms... nah, that's just a different add-on. I think [Readlang](https://readlang.com/) might be what you're looking for, although they might make you pay for certain features, I can't remember. 

My experience with language learning is that there's important point you hit after learning it for a while where you basically get the grammar enough to understand the structure of all the sentences, but you just need to fill in the gaps with verbs and nouns. Wordology has always been designed for people already past that hump in the learning curve - it's been consciously oriented towards intermediate learners from the start.

**Comment by jubalh** [comment]
Alright. Thanks though for making that plugin!
